Repository Netcracker/qubership-core-blue-green-state-monitor, pull requests merged in 2025-09, with the labels that each got.

#39 chore(deps): update spring to v3.4.9
  blue-green-state-monitor-spring/pom.xml
Labels: type:patch, branch:main, renovate:core

#35 chore(deps): update dependency org.projectlombok:lombok to v1.18.38
  pom.xml
Labels: renovate, type:patch

#46 chore(deps): update dependency org.mockito:mockito-core to v5.17.0
  blue-green-state-monitor-java/pom.xml
Labels: branch:main, renovate:core, type:minor

#54 chore(deps): update dependency org.apache.maven.plugins:maven-surefire-plugin to v3.5.4
  pom.xml
Labels: type:patch, branch:main, renovate:core, manager:maven, group:maven

#53 chore(deps): update netcracker/qubership-core-infra action to v1.0.9
  .github/workflows/maven-build.yaml
Labels: type:patch, branch:main, renovate:core, manager:github-actions
